name: "ESP RainMaker"
description: "ESP RainMaker integration addon for Home Assistant"
version: "1.0.17"
slug: "esp-rainmaker"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
host_network: true
map:
  - "share:rw"
options:
  email: ""
  password: ""
  profile: "global"
  api_port: 8100
schema:
  email: str
  password: password
  profile: str
  api_port: port